import { AppData } from "./types";

export const mockData: AppData = {
  clans: [
    {
      id: "clan-1",
      name: "Del Rosario",
      slug: "del-rosario",
      description: "A multi-generation family spread across regions.",
    },
    {
      id: "clan-2",
      name: "Okafor",
      slug: "okafor",
      description: "A growing clan with deep roots and new branches.",
    },
  ],
  memberships: [
    { clanId: "clan-1", role: "admin" },
    { clanId: "clan-2", role: "member" },
  ],
  currentUser: {
    id: "user-1",
    name: "Kati G.",
    email: "kati@example.com",
  },
  persons: [
    {
      id: "p-1",
      clanId: "clan-1",
      fullName: "Arturo Del Rosario",
      birthDate: "1948-04-12",
      deathDate: "2018-11-02",
      isAlive: false,
      gender: "M",
      branchRootId: "p-1",
      notes: "Community elder and historian.",
      stats: {
        occupation: "Teacher",
        location: "Manila",
        tags: ["Patriarch"],
      },
      createdAt: "2024-01-03T09:12:00Z",
    },
    {
      id: "p-2",
      clanId: "clan-1",
      fullName: "Elena Del Rosario",
      birthDate: "1951-07-19",
      isAlive: true,
      gender: "F",
      branchRootId: "p-1",
      notes: "Keeps the family archives.",
      stats: {
        occupation: "Archivist",
        location: "Quezon City",
        tags: ["Matriarch"],
      },
      createdAt: "2024-01-03T09:14:00Z",
    },
    {
      id: "p-3",
      clanId: "clan-1",
      fullName: "Marco Del Rosario",
      birthDate: "1975-03-02",
      isAlive: true,
      gender: "M",
      branchRootId: "p-1",
      notes: "Leads the family business.",
      stats: {
        occupation: "Entrepreneur",
        location: "Cebu",
      },
      createdAt: "2024-01-03T09:17:00Z",
    },
    {
      id: "p-4",
      clanId: "clan-1",
      fullName: "Isabella Del Rosario",
      birthDate: "1978-09-21",
      isAlive: true,
      gender: "F",
      branchRootId: "p-1",
      notes: "Coordinates family reunions.",
      stats: {
        occupation: "Event Planner",
        location: "Davao",
      },
      createdAt: "2024-01-03T09:18:00Z",
    },
    {
      id: "p-5",
      clanId: "clan-1",
      fullName: "Rafael Del Rosario",
      birthDate: "2002-12-09",
      isAlive: true,
      gender: "M",
      branchRootId: "p-1",
      notes: "University student with interest in family history.",
      stats: {
        occupation: "Student",
        location: "Manila",
      },
      createdAt: "2024-01-03T09:21:00Z",
    },
    {
      id: "p-6",
      clanId: "clan-1",
      fullName: "Amara Del Rosario",
      birthDate: "2005-06-14",
      isAlive: true,
      gender: "F",
      branchRootId: "p-1",
      notes: "Collects oral stories from elders.",
      stats: {
        occupation: "Research Assistant",
        location: "Cebu",
      },
      createdAt: "2024-01-03T09:22:00Z",
    },
    {
      id: "p-7",
      clanId: "clan-1",
      fullName: "Javier Santos",
      birthDate: "1973-10-11",
      isAlive: true,
      gender: "M",
      branchRootId: "p-7",
      notes: "Married into the clan.",
      stats: {
        occupation: "Architect",
        location: "Taguig",
      },
      createdAt: "2024-01-03T09:23:00Z",
    },
    {
      id: "p-8",
      clanId: "clan-1",
      fullName: "Nora Del Rosario",
      birthDate: "2010-02-04",
      isAlive: true,
      gender: "F",
      branchRootId: "p-1",
      notes: "Enjoys family gatherings.",
      stats: {
        occupation: "Student",
        location: "Cebu",
      },
      createdAt: "2024-01-03T09:25:00Z",
    },
    {
      id: "p-9",
      clanId: "clan-2",
      fullName: "Chidi Okafor",
      birthDate: "1965-08-08",
      isAlive: true,
      gender: "M",
      branchRootId: "p-9",
      notes: "Head of the Okafor family.",
      stats: {
        occupation: "Engineer",
        location: "Lagos",
      },
      createdAt: "2024-03-02T10:10:00Z",
    },
    {
      id: "p-10",
      clanId: "clan-2",
      fullName: "Adaeze Okafor",
      birthDate: "1968-05-27",
      isAlive: true,
      gender: "F",
      branchRootId: "p-9",
      notes: "Keeps recipes and traditions.",
      stats: {
        occupation: "Chef",
        location: "Lagos",
      },
      createdAt: "2024-03-02T10:12:00Z",
    },
    {
      id: "p-11",
      clanId: "clan-2",
      fullName: "Uche Okafor",
      birthDate: "1990-01-15",
      isAlive: true,
      gender: "M",
      branchRootId: "p-9",
      notes: "Focused on diaspora connections.",
      stats: {
        occupation: "Analyst",
        location: "London",
      },
      createdAt: "2024-03-02T10:14:00Z",
    },
  ],
  relationships: [
    {
      id: "r-1",
      clanId: "clan-1",
      parentId: "p-1",
      childId: "p-3",
      relationshipType: "parent",
    },
    {
      id: "r-2",
      clanId: "clan-1",
      parentId: "p-2",
      childId: "p-3",
      relationshipType: "parent",
    },
    {
      id: "r-3",
      clanId: "clan-1",
      parentId: "p-1",
      childId: "p-4",
      relationshipType: "parent",
    },
    {
      id: "r-4",
      clanId: "clan-1",
      parentId: "p-2",
      childId: "p-4",
      relationshipType: "parent",
    },
    {
      id: "r-5",
      clanId: "clan-1",
      parentId: "p-3",
      childId: "p-5",
      relationshipType: "parent",
    },
    {
      id: "r-6",
      clanId: "clan-1",
      parentId: "p-3",
      childId: "p-6",
      relationshipType: "parent",
    },
    {
      id: "r-7",
      clanId: "clan-1",
      parentId: "p-4",
      childId: "p-8",
      relationshipType: "parent",
    },
    {
      id: "r-8",
      clanId: "clan-2",
      parentId: "p-9",
      childId: "p-11",
      relationshipType: "parent",
    },
    {
      id: "r-9",
      clanId: "clan-2",
      parentId: "p-10",
      childId: "p-11",
      relationshipType: "parent",
    },
  ],
  positions: [
    { personId: "p-1", clanId: "clan-1", x: 0, y: 0 },
    { personId: "p-2", clanId: "clan-1", x: 220, y: 0 },
    { personId: "p-3", clanId: "clan-1", x: 110, y: 160 },
    { personId: "p-4", clanId: "clan-1", x: 360, y: 160 },
    { personId: "p-5", clanId: "clan-1", x: 0, y: 320 },
    { personId: "p-6", clanId: "clan-1", x: 220, y: 320 },
    { personId: "p-8", clanId: "clan-1", x: 420, y: 320 },
    { personId: "p-9", clanId: "clan-2", x: 0, y: 0 },
    { personId: "p-10", clanId: "clan-2", x: 220, y: 0 },
    { personId: "p-11", clanId: "clan-2", x: 110, y: 160 },
  ],
  suggestions: [
    {
      id: "s-1",
      clanId: "clan-1",
      createdAt: "2024-10-01T10:00:00Z",
      creatorEmail: "guest@example.com",
      targetType: "person",
      targetId: "p-5",
      action: "update",
      payload: {
        notes: "Recently moved to Singapore for graduate school.",
      },
      status: "pending",
    },
    {
      id: "s-2",
      clanId: "clan-1",
      createdAt: "2024-10-05T14:22:00Z",
      createdBy: "user-1",
      targetType: "person",
      targetId: "p-4",
      action: "update",
      payload: {
        location: "Davao",
      },
      status: "approved",
      reviewedBy: "user-1",
      reviewedAt: "2024-10-05T15:00:00Z",
    },
  ],
  changeEvents: [
    {
      id: "c-1",
      clanId: "clan-1",
      actorName: "Kati G.",
      actorId: "user-1",
      targetType: "person",
      targetId: "p-3",
      action: "update",
      diff: [
        { field: "notes", before: "Leads the family business.", after: "Leads the family foundation." },
      ],
      createdAt: "2024-09-18T09:30:00Z",
    },
    {
      id: "c-2",
      clanId: "clan-1",
      actorName: "Kati G.",
      actorId: "user-1",
      targetType: "relationship",
      targetId: "r-7",
      action: "create",
      diff: [
        { field: "parent", before: "-", after: "Isabella Del Rosario" },
        { field: "child", before: "-", after: "Nora Del Rosario" },
      ],
      createdAt: "2024-09-20T12:10:00Z",
    },
  ],
};
